name = "donna-executor"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "donna-executor-db"
database_id = ""

[[kv_namespaces]]
binding = "REGISTRY_KV"
id = ""

[triggers]
crons = ["0 * * * *"]
